CREATE TABLE IF NOT EXISTS `telegram_js` (
  `id` int NOT NULL AUTO_INCREMENT,
  `json` json NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;